FROM python:3
ADD audio_service.py /
ADD mic_map.json /
ADD raspberry_api.py /
ADD network_utils.py /
ADD config_gen.py /
ADD audio_logger.py /
ADD requirements.txt /
RUN pip install -r requirements.txt

